<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreeCol.Core\FreeCol.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ASCOM.Alpaca.Components" Version="3.1.0" />
  </ItemGroup>

</Project>
